### ISSUE TITLE
Table columns are not read when using MariaDB and an enum field

### ISSUE THREAD

**Issue by florentpoujol** [cloudstudio/resource-generator#10]
_tl;dr_ : Doctrine thinks MariaDB doesn't support the `enum` field type and throws an exception when encountering it, preventing the tool to process the table informations.  
No issue when the table doesn't have an enum field.

----

Hi !

I just brought Nova for my company and wanted to try your package, which seems super handy, but there seems to be an issue which it discovers table fields ?

When I choose the table in the "Create new Resource" I can see all the tables and I can see in the debug bar the `show columns from roles` request (for the roles table).

However, the `Title` or `Search` fields only display the tree default fields.

When I click on the "Continue" button I got the following error in the Chrome console and the following form only display 3 lines  (for the three default fields).

We use laravel 5.7.10, the last Nova 1.1.5 (but same thing with Nova v1.1.0), MariaDB 10.3.7. 

Here is the error and stacktrace as displayed in the console :

```
vendor.js?id=72b92cfcd11b931f56d4:92382 [Vue warn]: Invalid prop: type check failed for prop "tables". Expected Object, got Array.

found in

---> <Column>
       <Anonymous>
         <Root>
warn @ vendor.js?id=72b92cfcd11b931f56d4:92382
assertProp @ vendor.js?id=72b92cfcd11b931f56d4:93421
validateProp @ vendor.js?id=72b92cfcd11b931f56d4:93349
loop @ vendor.js?id=72b92cfcd11b931f56d4:95123
initProps @ vendor.js?id=72b92cfcd11b931f56d4:95156
initState @ vendor.js?id=72b92cfcd11b931f56d4:95097
Vue._init @ vendor.js?id=72b92cfcd11b931f56d4:96417
VueComponent @ vendor.js?id=72b92cfcd11b931f56d4:96587
createComponentInstanceForVnode @ vendor.js?id=72b92cfcd11b931f56d4:96099
init @ vendor.js?id=72b92cfcd11b931f56d4:95920
createComponent @ vendor.js?id=72b92cfcd11b931f56d4:97397
createElm @ vendor.js?id=72b92cfcd11b931f56d4:97344
updateChildren @ vendor.js?id=72b92cfcd11b931f56d4:97634
patchVnode @ vendor.js?id=72b92cfcd11b931f56d4:97725
updateChildren @ vendor.js?id=72b92cfcd11b931f56d4:97611
patchVnode @ vendor.js?id=72b92cfcd11b931f56d4:97725
updateChildren @ vendor.js?id=72b92cfcd11b931f56d4:97615
patchVnode @ vendor.js?id=72b92cfcd11b931f56d4:97725
patch @ vendor.js?id=72b92cfcd11b931f56d4:97885
Vue._update @ vendor.js?id=72b92cfcd11b931f56d4:94459
updateComponent @ vendor.js?id=72b92cfcd11b931f56d4:94577
get @ vendor.js?id=72b92cfcd11b931f56d4:94931
run @ vendor.js?id=72b92cfcd11b931f56d4:95008
flushSchedulerQueue @ vendor.js?id=72b92cfcd11b931f56d4:94770
(anonymous) @ vendor.js?id=72b92cfcd11b931f56d4:93626
flushCallbacks @ vendor.js?id=72b92cfcd11b931f56d4:93547
Promise.then (async)
microTimerFunc @ vendor.js?id=72b92cfcd11b931f56d4:93595
nextTick @ vendor.js?id=72b92cfcd11b931f56d4:93639
queueWatcher @ vendor.js?id=72b92cfcd11b931f56d4:94857
update @ vendor.js?id=72b92cfcd11b931f56d4:94998
notify @ vendor.js?id=72b92cfcd11b931f56d4:92488
reactiveSetter @ vendor.js?id=72b92cfcd11b931f56d4:92805
proxySetter @ vendor.js?id=72b92cfcd11b931f56d4:95089
(anonymous) @ resource-generator:1
Promise.then (async)
goToFields @ resource-generator:1
invoker @ vendor.js?id=72b92cfcd11b931f56d4:93816
fn._withTask.fn._withTask @ vendor.js?id=72b92cfcd11b931f56d4:93615

```

Tanks for you time !

**Comment by cloudstudio** [comment]
Hello @florentpoujol  I think doctrine is not working with MariaDB, we only test it with mysql.

I think working only with mysql, i try to check soon :)

**Comment by florentpoujol** [comment]
Hey ! Thanks for your anwser

But I apologize, I haven't properly investigated before opening the ticket.

The tool actually works for most tables, even with MariaDB.  

It does not however when the table contain an **enum** type, because Doctrine thinks that MariaDB does'nt support it and throws the following exception from `ResourceGeneratorService::getColumnType()`.  
(MariaDB 10.3.7 definitely supports enums)

```
Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it. at /myapp/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:479)
```

Putting a quick try/catch in this method and returning `'enum'` when catching DBALExceptions seems to work, I can access the table with all the fields but all the fields types are either 'text' or 'relation' (no 'integer' or 'datetime' even when the fields were recognized of that type)...

I already outgrown the need for the generator, so I won't bother doing more.  
I will just close the issue and update the title/first post.

Tanks for your time.

**Comment by cloudstudio** [comment]
@florentpoujol perfect ! so enjoy it :)
