### ISSUE TITLE
[FR] Allow cutomizing Resources Namespace

### ISSUE THREAD

**Issue by mathieutu** [cloudstudio/resource-generator#13]
Hi,
My resources are in `App\Nova\Resources`, so the generated resources are not in a proper place.

The namespace could be anything actually (like `App\Admin`), and it would be cool if it could be personalized in a config file.

Thanks,
Matt'

**Comment by cloudstudio** [comment]
@mathieutu done ! please remove /storage/nova-resource-generator.json and save settings.

Let me know if is all right :)

**Comment by mathieutu** [comment]
Thanks. I'm currently using my fork because of the PR I made but I will merge that.

Why not using standard laravel config files instead of this json?

**Comment by cloudstudio** [comment]
@mathieutu merged, thanks for this :)

No concrete reason, anyway if you want make changes, PR are welcome!!.

I wait for your confirmation, before closing this

Thanks mate !

**Comment by mathieutu** [comment]
It's great!
Thx!
