### ISSUE TITLE
[FR] allow custom model path or chose it from a list !

### ISSUE THREAD

**Issue by atmonshi** [cloudstudio/resource-generator#14]
the `$model` is set by the generator and it does not match my current models structures 
(grouping the models with multi subfolders) ,

it will be great if I can chose a model file from a list or set the full path for it ,

loved the package by the way ❤️ 

thank you .

**Comment by cloudstudio** [comment]
Hello @wa7eedem  i love you love this :)

It is a very specific feature, if more people want this, we can study it.

Thanks for you time!

**Comment by mixartemev** [comment]
Hi guys, I guess it relates to #16

**Comment by cloudstudio** [comment]
@mixartemev thanks! merged

**Comment by atmonshi** [comment]
@mixartemev  thank you for the PR , 

but unfortunately the generated file is placed in `\App` folder , not in the default one` \App\Nova` and its look like : 

<img width="595" alt="screen shot 2018-11-22 at 10 01 39 pm" src="https://user-images.githubusercontent.com/1952412/48919221-8a777f80-eea2-11e8-9921-cea5de9c6184.png">


for me , I had to edit the files manually ,,

- move the Resource file from `\App` to `\App\Nova\Resources` 
- edit the models from `\App\Models\WCountry::class` to `\App\Models\World\WCountry::class`
- change the namespace for the resource


I Really think if there is a way to set the path manually in the Create new Resource form will help a lot of cases .


-- edit : 
in my case I didn't check the `Create Model` option , I tested it with 'Create Model' and the model file is in the correct place  , but not the resource file

<img width="575" alt="screen shot 2018-11-22 at 10 20 13 pm" src="https://user-images.githubusercontent.com/1952412/48919601-d3c8ce80-eea4-11e8-8e9a-c38634fece11.png">

**Comment by mixartemev** [comment]
@wa7eedem 
I understood your problem finally! Probably you have old settings file `/storage/nova-resource-generator.json` without `resource` section. You must remove it, new file will be generated automatically. Than you will see Resource folder input at settings screen 
<img width="734" alt="2018-11-23 14 42 15" src="https://user-images.githubusercontent.com/5181924/48941833-2dc1a680-ef2e-11e8-90b0-1a8d52d6a686.png">
After then resource file will be generate in your Nova dir with correct namespace.

**Comment by cloudstudio** [comment]
Yep ! confirm is all right :)
thanks @mixartemev

**Comment by atmonshi** [comment]
OK , my bad , now it's clear :)
I see the option Resource folder and its works fine 

I still hoping for setting the path manually per resource , but now it's will be OK ..

thank you all for the help .

**Comment by cloudstudio** [comment]
@wa7eedem for now is the solution, but in v2 we work in a settings panel in each model, so you can configure some things :P
