### ISSUE TITLE
Search fields when creating resource

### ISSUE THREAD

**Issue by mathieutu** [cloudstudio/resource-generator#15]
Hi, 
When creating a resource, the `search fields` field is in `display:none` and when displayed manually, it has no column available.

Is it an issue? Have I done something wrong?

Thanks.

<img width="834" alt="screen shot 2018-11-22 at 10 15 59" src="https://user-images.githubusercontent.com/11351322/48893922-bca4c500-ee41-11e8-8e22-b7b201b8f1ff.png">

**Comment by cloudstudio** [comment]
Looking this one right now!

**Comment by cloudstudio** [comment]
Fixed! thanks

**Comment by mathieutu** [comment]
Thank you for being so quick with issues/PR, you rock's!

Do you know when a release could be tagged?

**Comment by Krato** [comment]
It is: https://github.com/cloudstudio/resource-generator/releases/tag/1.1.0
