### ISSUE TITLE
Class \Cloudstudio\ResourceGenerator\ResourceGenerator not found

### ISSUE THREAD

**Issue by levi-beers** [cloudstudio/resource-generator#2]
I've tried the installation & registration method for the resource-generator but receive: Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Cloudstudio\ResourceGenerator\ResourceGenerator' not found

I'm using Nova 1.1.4

**Comment by cloudstudio** [comment]
Hello @levi-beers you install correctly right ?

```
composer require cloudstudio/resource-generator
```
Maybe try :
```
php artisan package:discover
```

**Comment by levi-beers** [comment]
I made the mistake of running composer from the nova directory when installing cloudstudio/resource-generator instead of my main Laravel app directory. My apologies, total newbie mistake.

**Comment by cloudstudio** [comment]
So enjoy it !
