### ISSUE TITLE
Feature Request - Change default value for Show In fields

### ISSUE THREAD

**Issue by chrisswany** [cloudstudio/resource-generator#21]
I have a fair amount of tables that have a lot of columns and in most resources I only want the first 3-5 columns to show anywhere other than forms or details.  When I create a resource I will have to go change this field for the often 20+ columns that are only needed to forms.

My request would be to be able to change default value of show in field to something other than all.  Also it would be ideal that maybe you could have a setting to split into two default values.  Say you want first 5 fields to alway be all and the rest to onlyonforms.  It would give a lot more flexibility and save time for someone building resources on a lot of tables with lots of columns.  

If not going to happen could you pint me in direction where I can make that change for my local instance?

**Comment by cloudstudio** [comment]
@chrisswany i have same problem in one project, change for now :)

**Comment by cloudstudio** [comment]
![Captura de pantalla 2019-03-20 a las 16 16 21](https://user-images.githubusercontent.com/3589377/54696230-c3132700-4b2b-11e9-89f2-e17ec926cbc1.png)
