### ISSUE TITLE
Problem with indenting

### ISSUE THREAD

**Issue by kentsigurdsen** [cloudstudio/resource-generator#23]
Hello,

When generating a new resource the code looks real messy.

Is there any way to fix this?

Look at the attatched screenshot for further explaining. 

<img width="945" alt="Skjermbilde 2019-06-16 kl  23 43 14" src="https://user-images.githubusercontent.com/9360800/59569954-daad6d80-9090-11e9-8012-5a9ad56bd133.png">

**Comment by cloudstudio** [comment]
Yep, know problem :P 

At the moment we can't do anything, I recommend use a IDE formatter something like this : 

https://marketplace.visualstudio.com/items?itemName=vs-publisher-599079.CodeFormatter
