### ISSUE TITLE
Receiving Undefined method camel_caseI()

### ISSUE THREAD

**Issue by lauhakari** [cloudstudio/resource-generator#24]
Hi there!

Found this package today, seemd very nice as I have a bunch of tables to create as Resources. But after install and went to create my first resource I encountered this little error. :/

`Call to undefined function Cloudstudio\ResourceGenerator\Http\Services\camel_case()`

**Comment by cloudstudio** [comment]
@lauhakari Fixed for Laravel 6 in 1.4
