### ISSUE TITLE
Add Laravel 6 support

### ISSUE THREAD

**Issue by num3r06** [cloudstudio/resource-generator#28]
Hi,
Seems to be not compatible with laravel 6 fresh installation 
Thx

**Comment by cloudstudio** [comment]
@num3r06  can you check it again ? 

Thanks

**Comment by num3r06** [comment]
This it's the error
![Immagine](https://user-images.githubusercontent.com/7809704/66290826-8bf63e80-e8e0-11e9-80e7-373ca0338742.png)
Also this is the error while saving settings

![Immagine1](https://user-images.githubusercontent.com/7809704/66290937-d37cca80-e8e0-11e9-97b2-8034d7f70df2.png)

**Comment by cloudstudio** [comment]
@num3r06 released new version, remeber clear views 👍
