### ISSUE TITLE
Call to undefined function str_plural()

### ISSUE THREAD

**Issue by suretarget** [cloudstudio/resource-generator#29]
Fresh install Laravel 6 & Nova v2.4.0.
Package: "cloudstudio/resource-generator": "^1.4"

Edited: Look like all helper function have been removed from Laravel 6.
`/vendor/cloudstudio/resource-generator/resources/views/templates/resource.blade.php`

Thanks.

**Comment by cloudstudio** [comment]
@suretarget released new version, remeber clear views 👍
