### ISSUE TITLE
Please check all data. You have some mandatory field.

### ISSUE THREAD

**Issue by ArtMin96** [cloudstudio/resource-generator#30]
First all thanks for this amazing package.

I don't think that it's a bug but I can't create the resource with relation.

Migration screenshots bellow.

![screenshot](https://user-images.githubusercontent.com/29732308/90069878-01eae380-dd04-11ea-8ab5-f63836adc681.png)
![screenshot_1](https://user-images.githubusercontent.com/29732308/90069902-09aa8800-dd04-11ea-9933-65704e49c5d9.png)

**Comment by cloudstudio** [comment]
Hello @ArtMin96 , what is the error exactly?

**Comment by ArtMin96** [comment]
Hi @cloudstudio , Thanks for reply. Error "Please check all data. You have some mandatory field."

![download (11)](https://user-images.githubusercontent.com/29732308/90282847-24097080-de80-11ea-960e-11861c2459e3.png)

![download](https://user-images.githubusercontent.com/29732308/90282870-2f5c9c00-de80-11ea-82da-9fb2c7e942b8.png)

![download (1)](https://user-images.githubusercontent.com/29732308/90282887-34215000-de80-11ea-8037-587b51217417.png)

**Comment by cloudstudio** [comment]
Hello @ArtMin96 you need press in "Set Relation" and configure field and model, and I think all work fine.

**Comment by ArtMin96** [comment]
> Hello @ArtMin96 you need press in "Set Relation" and configure field and model, and I think all work fine.

Thats problem because Set Relation button not working. Popup not opening

**Comment by cloudstudio** [comment]
@ArtMin96 probably you have a console error.

I see that you have different packages installed, it may be giving some js error in one of them, can you check it ?

**Comment by ArtMin96** [comment]
> @ArtMin96 probably you have a console error.
> 
> I see that you have different packages installed, it may be giving some js error in one of them, can you check it ?

There is no error in console. But you right, I think problem is coming from other nova package. Thanks!
