### ISSUE TITLE
Usage of database prefix

### ISSUE THREAD

**Issue by pegelf** [cloudstudio/resource-generator#33]
Thank you for that Laravel Nova package.

I tried it out on our project and had the problem, that it uses the database prefix as a part of the resource name. We defined the prefix in the config/database.php file, so every database table starts with "cms_".

Could you maybe add support for that function?

**Comment by cloudstudio** [comment]
hello @pegelf I don't understand the problem very well, in principle the name of the table/database is not relevant, it can be anything.

**Comment by pegelf** [comment]
Yes, it can be everything but it will be included in the name. For example when I have these tables:
- cms_customers
- cms_products
- cms_users

Then these models will be generated:
- CmsCustomers
- CmsProducts
- CmsUsers

But of course it should be:
- Customers
- Products
- Users

To achieve that, I think the easiest way to support database prefixes is to read the setting in config/database.php.
