### ISSUE TITLE
PhpFormat

### ISSUE THREAD

**Issue by johnpaulmedina** [cloudstudio/resource-generator#6]
@cloudstudio 

I forked the REPO. I was thinking of using this to run `phpfmt` on the created files. I was gonna put some time in to make a pull-request if you are interested. I use this in sublime and works well with some great config options like PSR etc... Would be best to include it as part of a requirement and execute the python script against the generated PHP files.

https://github.com/nanch/phpfmt_stable

What do you think?

**Comment by cloudstudio** [comment]
Hello @johnpaulmedina! i use in sublime text 3 too :)

We work in v2 soon, we try to format all files by default :P 

I have doubts with https://github.com/nanch/phpfmt_stable maybe not everyone has python installed in their machines, and can't run this script, we can talk about it.

Tanks for all!

**Comment by johnpaulmedina** [comment]
Understandable. Was just throwing a quick solution out, maybe even a remote formatter which executes phpfmt :) lol. Nice job on the generators by the way very simple to use and its exactly what I would do!!
