### ISSUE TITLE
PageReload

### ISSUE THREAD

**Issue by johnpaulmedina** [cloudstudio/resource-generator#7]
Page reload seems to not work

**Comment by Krato** [comment]
Hello @johnpaulmedina. Can you show you your console logs? Thanks

**Comment by atmonshi** [comment]
I have the same here , although nothing on the console , but for me the reasons is that the `$model` is set by the generator and its does not match my current models structures (grouping the models with multi subfolders) , I hope you allow to customize the `$model` name , 
loved the package by the way :)

**Comment by cloudstudio** [comment]
Fixed 

@wa7eedem please generate new issue and i check for you :)
